# arch/arm/mach-nxp2120/Makefile
#
# Copyright 2011 mostitech co., ltd.
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

# Core support for nxp2120 system

obj-$(CONFIG_CPU_NXP2120)	+= cpu.o
obj-$(CONFIG_CPU_NXP2120)	+= lldebug.o

# machine support

obj-$(CONFIG_MACH_MOST2120)	+= mach-most2120.o

