#
# Copyright 2010 Nexell Co.
#
# Makefile for the Nexell Display Control

obj-$(CONFIG_V4L2_DRIVER_NEXELL)  	+= nx_vip_v4l2.o nx_vip_core.o
obj-$(CONFIG_VIDEO_DEC_TVP5150)	+= sub_tvp5150.o
obj-$(CONFIG_CAMERA1_MT9M111)    += mt9m111.o
obj-$(CONFIG_CAMERA1_POA030)    += poa030r.o
obj-$(CONFIG_CAMERA1_HI702)    += hi702.o
obj-$(CONFIG_CAMERA1_HI161)    += hi161.o
obj-$(CONFIG_CAMERA2_MT9M111)    += mt9m111.o
obj-$(CONFIG_CAMERA2_POA030)    += poa030r_2.o
obj-$(CONFIG_CAMERA2_HI161)    += hi161.o
